# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: projects/click_custom_proto_parser/joey.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'projects/click_custom_proto_parser/joey.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-projects/click_custom_proto_parser/joey.proto\"\x94\x01\n\x10YourProtoMessage\x12\x18\n\x0bscenario_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04tags\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05req_1\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05req_2\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x0e\n\x0c_scenario_idB\x07\n\x05_tagsB\x08\n\x06_req_1B\x08\n\x06_req_2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'projects.click_custom_proto_parser.joey_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_YOURPROTOMESSAGE']._serialized_start=50
  _globals['_YOURPROTOMESSAGE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
